services:
  - type: web
    name: personal-blog
    env: node
    nodeVersion: 18
    buildCommand: npm install && npm run build
    startCommand: npm run start
    port: 3000
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    resources:
      cpu: 1
      memory: 1GB
